apiVersion: v1
kind: Secret
metadata:
  name: secret-volume
  namespace: default
type: kubernetes.io/basic-auth
# type: Qpaque 也可以用 Qpaque 类型
data:
  username: cm9vdA== # key名称: username
  password: MTIzNDU2 # key名称: password
---
apiVersion: v1
kind: Pod
metadata:
  name: "pod-secret-volume"
  namespace: default
  labels:
    app: "pod-secret-volume"
spec:
  containers:
  - name: pod-secret-volume
    image: "wangxiaochun/nginx:1.20.0"
    ports:
    - containerPort: 80
      name: http
    volumeMounts:
    - name: secret-volume
      mountPath: /secret/
  volumes:
  - name: secret-volume
    secret:
      secretName: secret-volume
  restartPolicy: Always
