apiVersion: v1
kind: Secret
metadata:
  name: secret-mysql
  namespace: default
type: kubernetes.io/basic-auth
# type: Qpaque 也可以用 Qpaque 类型
data:
  username: cm9vdA== # key名称: username
  password: NjU0MzIx # key名称: password
---
apiVersion: v1
kind: Pod
metadata:
  name: "pod-secret-mysql-init"
  namespace: default
  labels:
    app: "pod-secret-mysql-init"
spec:
  containers:
  - name: pod-secret-mysql-init
    image: "mysql:8.0"
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: secret-mysql
          key: password
    ports:
    - containerPort: 3306
      name: mysql
  restartPolicy: Always
