apiVersion: v1
kind: Pod
metadata:
  name: "volume-nfs-pod-new"
  namespace: default
  labels:
    app: "volume-nfs-pod"
spec:
  nodeName: k8s-node2 # 指定在node2节点运行 Pod
  containers:
  - name: volume-nfs-pod-new
    image: "redis:6.2.5"
    ports:
    - containerPort: 6379
      name: redis
    volumeMounts:
    - name: redis-data-path
      mountPath: /data
  volumes:
  - name: redis-data-path
    nfs:
      server: 10.0.0.50
      path: /nfs-data
  restartPolicy: Always
