apiVersion: v1
kind: Pod
metadata:
  name: "pod-nginx"
  namespace: default
  labels:
    app: "pod-nginx"
spec:
  containers:
  - name: pod-nginx
    image: "wangxiaochun/nginx:1.20.0"
    ports:
    - containerPort: 80
      name: http
    volumeMounts:
    - name: volume-nginx
      mountPath: "/usr/share/nginx/html"
  volumes:
  - name: volume-nginx
    persistentVolumeClaim:
      claimName: pvc-test
  restartPolicy: Always
