kind: ConfigMap
apiVersion: v1
metadata:
  name: cm-nginx-index
  namespace: default
data:
  index.html: "Nginx ConfigMap Page!" # 单行内容的文件生成的configMap
---
apiVersion: v1
kind: Pod
metadata:
  name: "pod-nginx-configmap"
  namespace: default
  labels:
    app: "pod-nginx-conf"
spec:
  containers:
  - name: nginx
    image: "wangxiaochun/nginx:1.20.0"
    ports:
    - containerPort: 80
      name: http
    volumeMounts:
    - name: nginx-conf
      mountPath: /etc/nginx/conf.d/
      readOnly: true
    - name: nginx-index
      mountPath: /usr/share/nginx/html/
  volumes:
  - name: nginx-conf
    configMap:
      name: cm-nginx-conf-files
      optional: true
  - name: nginx-index
    configMap:
      name: cm-nginx-index
      optional: false
  restartPolicy: Always
