kind: ConfigMap
apiVersion: v1
metadata:
  name: cm-volume
  namespace: default
data:
  author: zhongzhiwei@kubesphere.io
  file.conf: |
    [app]
    config1: value1
    config2: value2
---
apiVersion: v1
kind: Pod
metadata:
  name: "pod-volume-test"
  namespace: default
  labels:
    app: "pod-volume-test"
spec:
  containers:
  - name: pod-volume-test
    image: "wangxiaochun/nginx:1.20.0"
    volumeMounts:
    - name: volume-config
      mountPath: /cmap/
  volumes:
  - name: volume-config # 指定卷名
    configMap:
      name: cm-volume # 指定卷来自 configMap
  restartPolicy: Always
